### ISSUE TITLE
[Feature Request]  Years and Months for Interval Hints

### ISSUE THREAD

**Issue by cesar-programs** [KerfuffleV2/logseq-plugin-interval-hints#2]
Hello, @KerfuffleV2.

I believe a nice feature for the `Interval Hints` plug-in would be to portray the time in years and months if the interval falls within that span.

Thank you.

**Comment by KerfuffleV2** [comment]
Would calculating it the naive way work for you? In other words, considering a month to be 30 days and a year to be 365 days.

**Comment by KerfuffleV2** [comment]
I'm going to close this since it's been a long time without any response to my question. Also, #3 may be what you wanted anyway.

If you want it reopened or have something to add, please feel free to comment again. (You might need to @ me to make sure I see it.)
