### ISSUE TITLE
Edit current page fails with: Path does not exist

### ISSUE THREAD

**Issue by mrdavidlaing** [KerfuffleV2/logseq-plugin-interval-hints#5]
## What happens
Whilst all the other menu options work, when I try the "Edit current page" option
![image](https://github.com/KerfuffleV2/logseq-plugin-interval-hints/assets/227505/57467456-2609-46e0-be53-a25916fd8db8)

VS Code opens showing the following error:

![image](https://github.com/KerfuffleV2/logseq-plugin-interval-hints/assets/227505/3242a965-9efc-43f9-ac6f-8b770b7a1cda)

## What I expect to happen
The current page is opened in VSCode without an error

## Ideas
It looks like its trying to open an absolute path - `/pages/Note.md` without including the full path to the graph folder.

## Versions
Open in VS Code: v0.0.5
OS: Mac OS 13.4 (22F66)
Logseq: 0.9.8 (0.9.8)
VS Code: 1.78.2 (Universal)

**Comment by KerfuffleV2** [comment]
Are you saying this behavior _only_ occurs when the `plugin-interval-hints` extension is enabled?

**Comment by mrdavidlaing** [comment]
😵‍💫 Apologies - I logged this bug agains the wrong repo!!

https://github.com/rebornix/logseq-open-in-code/issues/7#issuecomment-1575556977

**Comment by KerfuffleV2** [comment]
Not a problem. Have a good weekend!
